logging:
  config: classpath:log4j2-dev.xml

logTracer:
  maxPrintLength:
    singleParam: 5000
    returnValue: 5000

druid:
  initialSize: 1
  minIdle: 1
  maxActive: 20
  maxWait: 3000
  useUnfairLock: true
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  poolPreparedStatements: false
  maxPoolPreparedStatementPerConnectionSize: 50
  validationQuery: SELECT 1
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false

dataSource:
  xxxDbMaster:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.170.56:3306/xxx?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false
    username:
    password:

redis:
  key:
    prefix: dipao
    maxLength: 80
  hostName: 172.16.170.70
  password:
  defaultDbIndex: 0
  port: 6379
  timeout: 1000
  pool:
    maxIdel: 100
    maxTotal: 200
    minIdel: 10
    maxWaitMillis: 2000